### ISSUE TITLE
Why did not the attachment support files with Chinese Name?

### ISSUE THREAD

**Issue by AstridWang** [kootenpv/yagmail#127]
I  found when my attached files were  with English Name, I could received the email with attachments normally. But when I changed the attached files' name with Chinese, i could received the email but without attachments.
Is there any chance to support Chinese filename?

**Comment by kootenpv** [comment]
I have no idea what is necessary for that, but I'm very curious. I hope someone could pick this up.

**Comment by csingley** [comment]
What happens if you say:
`os.path.isfile(excel_path)`

**Comment by AstridWang** [comment]
Oh..........It returned a False. What should I do?

**Comment by csingley** [comment]
Well, you need to fix `excel_path`.
First thing to try is to write:
`excel_path = os.path.join(cur_file_dir(), '收款明细9月份.xlsx')`

If that doesn't work, you can try to inspect the output of commands like:
`os.listdir(cur_file_dir())`
`os.path.supports_unicode_filenames`
`sys.getfilesystemencoding()`

**Comment by bdochen** [comment]
it can not attach Chinese name file, what should i do?  Thank you !

error for example:
receiver=['xxxxx@qq.com','E:\商户租金自动发送\租户邮箱及附件名称.xlsx']


Traceback (most recent call last):
  File "E:\商户租金自动发送\yagmail_20181227.py", line 10, in <module>
    yag.send(receiver, subject, contents)
  File "E:\Python\lib\site-packages\yagmail\sender.py", line 146, in send
    to, subject, contents, attachments, cc, bcc, headers
  File "E:\Python\lib\site-packages\yagmail\sender.py", line 115, in prepare_send
    validate_email_with_regex(email_addr)
  File "E:\Python\lib\site-packages\yagmail\validate.py", line 110, in validate_email_with_regex
    raise YagInvalidEmailAddress(emsg)
yagmail.error.YagInvalidEmailAddress: Emailaddress "E:\商户租金自动发送\租户邮箱及附件名称.xlsx" is not valid according to RFC 2822 standards

**Comment by kootenpv** [comment]
Still hoping someone knows the whole story here.

**Comment by csingley** [comment]
I think the whole story here is that the user wasn't properly specifying a file path.  This is not a problem with your application.

This is what wasn't working for her, working on my box:

```
In [1]: import os                                                                                                                                                                       

In [2]: cwd = os.getcwd()                                                                                                                                                               

In [3]: path = os.path.join(cwd, "大圖.jpg")                                                                                                                                            

In [4]: os.path.isfile(path)                                                                                                                                                            
Out[4]: True

In [5]: with open(path, 'rb') as f: 
   ...:     data = f.read() 
   ...:                                                                                                                                                                                 

In [6]: data[:20]                                                                                                                                                                       
Out[6]: b'\xff\xd8\xff\xe1,\x7fExif\x00\x00II*\x00\x08\x00\x00\x00'

In [7]: import sys                                                                                                                                                                                                                                                                                    

In [8]: sys.version                                                                                                                                                                     
Out[8]: '3.7.3 (default, Mar 26 2019, 21:43:19) \n[GCC 8.2.1 20181127]'


```

**Comment by 4linuxfun** [comment]
I'm using foxmail client,and if i sent a mail with a Chinese file ,it will not show,but the web server will show it .(maybe the client question).When I change the content type to "Content-Type: application/octet-stream".The client show the file.
