### ISSUE TITLE
MIMEPart alternative support

### ISSUE THREAD

**Issue by oernster** [kootenpv/yagmail#19]
Using the code suggested here:
http://stackoverflow.com/questions/32911945/how-do-i-send-email-line-feeds-python-3-in-plain-text-mode-as-a-mime-alternate-w

I made slight modifications.  I used '' (empty string) as the filename.  Recipients was passed as a list instead of just one string.  I was keen to see MIMEpart alternative supported.  My understanding of this is you send both HTML and text in your email to a receiver and the receiver's email client has a setting to view as pure text or pure HTML.  That said, it should only display the text part or only display the HTML part.  At present if you view HTML in Thunderbird on Linux Mint (Ubuntu/deb variant), you see poorly formatted HTML (not what I sent) and the text below in HTML viewing mode.  In text viewing mode I see the HTML part with tags removed AND the text part below.  Basically I should see one OR the other, not both HTML and text in either case.  Also, the HTML is broken even in HTML mode but perhaps that is another ticket.

**Comment by oernster** [comment]
I think is has something to do with _preparemessage.  There is a dictionary search for headers.  I think we need to set headers appropriately.  Initially, somewhat naively I set headers in the send function to 'alternative' but it's a dictionary and I have no idea what the key / value pairs should be; though I assume the value is the 'alternative' part.

**Comment by oernster** [comment]
I noticed on the command line that it was complaining about missing lxml.  I pip install this (I'm using python 3 in virtualenv).  However, I now see this error result:

Traceback (most recent call last):
  File "etest.py", line 107, in <module>
    test_yag()
  File "etest.py", line 103, in test_yag
    yag.send(to=recipients, headers={'Content-Type':'text/alternative; charset=utf-8'}, subject='title', contents=contents)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/yagmail/yagmail.py", line 98, in send
    addresses, subject, contents, use_cache, headers)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/yagmail/yagmail.py", line 213, in _prepare_message
    contents, use_cache)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/yagmail/yagmail.py", line 279, in _prepare_contents
    content_object = self._get_mime_object(content)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/yagmail/yagmail.py", line 362, in _get_mime_object
    html_tree = lxml.html.fromstring(content_string)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/lxml/html/__init__.py", line 726, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/home/oliver/Development/ums/env3/lib/python3.4/site-packages/lxml/html/__init__.py", line 614, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1709, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105106)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:99534)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95065)
lxml.etree.XMLSyntaxError: None


I had previously updated the send method to include headers={'Content-Type':"'text/relative';charset='utf-8'"}

**Comment by oernster** [comment]
Note that removing the headers parameter produces the same result.  It seems the lxml dependency breaks yagmail in it's current form.

**Comment by kootenpv** [comment]
I can reproduce the bug when you set the first arguments of the list (instead of the filename in this case) to ''.

It tries to parse `''` which fails.

Though, please, contents can be mixed and it would make no sense to add `''` to it (though I will take care of it, if you want to send a message just don't use '' as an argument). 

"First argument" in this case (filename) is nothing special, just omit it.

    # works
    contents = ['/local/file.png', 'some text',
                '<b><a href="https://github.com/kootenpv/yagmail">a link</a></b>']

    # works
    contents = ['some text', '<b><a href="https://github.com/kootenpv/yagmail">a link</a></b>']

    # doesn't work
    contents = ['', 'some text',
                      '<b><a href="https://github.com/kootenpv/yagmail">a link</a></b>']

**Comment by oernster** [comment]
Thanks for the advice and very swift response to all my issues.  The problem is resolved if I remove '' as the first parameter as you described which is great, thanks.

**Comment by kootenpv** [comment]
Great, I'll regard it as closed!
