### ISSUE TITLE
Error in parsing string

### ISSUE THREAD

**Issue by moghadas76** [kootenpv/yagmail#191]
Traceback (most recent call last):
  File "/home/user/Documents/project/license_manager/venv/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/home/user/Documents/project/license_manager/venv/lib/python3.6/site-packages/bpython/curtsies.py", line 221, in main
    exit_value = repl.mainloop(True, paste)
  File "/home/user/Documents/project/license_manager/venv/lib/python3.6/site-packages/bpython/curtsies.py", line 133, in mainloop
    self.process_event_and_paint(e)
  File "/home/user/Documents/project/license_manager/venv/lib/python3.6/site-packages/bpython/curtsies.py", line 107, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/home/user/Documents/project/license_manager/venv/lib/python3.6/site-packages/bpython/curtsiesfrontend/repl.py", line 1623, in paint
    wcswidth(self.current_stdouterr_line)
  File "/home/user/Documents/project/license_manager/venv/lib/python3.6/site-packages/wcwidth/wcwidth.py", line 245, in wcswidth
    wcw = wcwidth(char, unicode_version)
TypeError: unhashable type: 'FmtStr'

**Comment by kootenpv** [comment]
Does not appear related to yagmail.

**Comment by moghadas76** [comment]
I was running in bpython. Does this its reason?

**Comment by kootenpv** [comment]
Your stack trace shows no mention of yagmail, and its thus not related.
