### ISSUE TITLE
Well,I tried to run the code on python anywhere and this is what it happened ? But it works fine in the ide !

### ISSUE THREAD

**Issue by arixank** [kootenpv/yagmail#193]
Traceback (most recent call last):
  File "/home/picklebot/picklebot.py", line 38, in <module>
    mail_it()
  File "/home/picklebot/picklebot.py", line 31, in mail_it
    server.send(to=to, subject=subject, contents=[
  File "/home/picklebot/.local/lib/python3.8/site-packages/yagmail/sender.py", line 153, in send
    self.login()
  File "/home/picklebot/.local/lib/python3.8/site-packages/yagmail/sender.py", line 206, in login
    self._login(self.credentials)
  File "/home/picklebot/.local/lib/python3.8/site-packages/yagmail/sender.py", line 213, in _login
    self.login()
    self.smtp = self.connection(self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 807, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by arixank** [comment]
why is it closed ??
