### ISSUE TITLE
import failing in Python 3.4.4 WinXP

### ISSUE THREAD

**Issue by abubelinha** [kootenpv/yagmail#212]
Apparently, my installation worked fine:
```Python
C:\Dropbox\python>c:\python34\scripts\pip install yagmail
Requirement already satisfied: yagmail in c:\python34\lib\site-packages (0.14.256)
Requirement already satisfied: premailer in c:\python34\lib\site-packages (from yagmail) (3.9.0)
Requirement already satisfied: cssselect in c:\python34\lib\site-packages (from premailer->yagmail) (1.1.0)
Requirement already satisfied: cssutils in c:\python34\lib\site-packages (from premailer->yagmail) (1.0.2)
Requirement already satisfied: lxml in c:\python34\lib\site-packages (from premailer->yagmail) (4.3.1)
Requirement already satisfied: cachetools in c:\python34\lib\site-packages (from premailer->yagmail) (3.1.0)
Requirement already satisfied: requests in c:\python34\lib\site-packages (from premailer->yagmail) (2.21.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python34\lib\site-packages (from requests->premailer->yagmail) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python34\lib\site-packages (from requests->premailer->yagmail) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python34\lib\site-packages (from requests->premailer->yagmail) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in c:\python34\lib\site-packages (from requests->premailer->yagmail) (2018.4.16)
```

But then I can't use it:

```Python
C:\>c:\python34\python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import yagmail

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python34\lib\site-packages\yagmail\__init__.py", line 7, in <module>
    from yagmail.sender import SMTP
  File "c:\python34\lib\site-packages\yagmail\sender.py", line 14, in <module>
    from yagmail.message import prepare_message
  File "c:\python34\lib\site-packages\yagmail\message.py", line 66
raise TypeError(f'{a} must be a valid filepath or file handle (instance of io.IOBase). {a} is of type {type(a)}')

SyntaxError: invalid syntax
>>>
```

Any hints?

**Comment by kootenpv** [comment]
F string won't work with such an old python.

I recommend you upgrade python, we're at 3.10 now :)

**Comment by abubelinha** [comment]
You could have upgraded the info about Python versions here:
https://pypi.org/project/yagmail/

Python 3.4 is clearly listed there.

Also, that’s the newest Python version available for my OS. 
I want to use this 32bit Windows XP computer so that’s my only chance.
