### ISSUE TITLE
SMTPAuthenticationError when trying to send. "BadCredentials"

### ISSUE THREAD

**Issue by drscotthawley** [kootenpv/yagmail#217]
Hi. I'm able to  yagmail.register with username & password (copied from my password store) with no errors, but when I try to send, I get...

```
>>> yag.send('myrealaddress@mydomain.com', subject = None, contents = 'Hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/student/envs/dlaie/lib/python3.9/site-packages/yagmail/sender.py", line 153, in send
    self.login()
  File "/home/student/envs/dlaie/lib/python3.9/site-packages/yagmail/sender.py", line 206, in login
    self._login(self.credentials)
  File "/home/student/envs/dlaie/lib/python3.9/site-packages/yagmail/sender.py", line 225, in _login
    self.smtp.login(self.user, password)
  File "/usr/lib/python3.9/smtplib.py", line 745, in login
    raise last_exception
  File "/usr/lib/python3.9/smtplib.py", line 734, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 657, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e13sm4003804qka.117 - gsmtp')
>>> 
```
It's the right username & password.   I have "Allow Less Secure Apps" enabled on Gmail as per another Issue advised. 

How does one fix this?

**Comment by drscotthawley** [comment]
This started working for reasons unclear to me.  "Allow Less Secure Apps" needed to be enabled on Google Security Settings though. 
Closing.
