### ISSUE TITLE
python3 - SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by schef** [kootenpv/yagmail#25]
I installed yagmail using pip for python3.
But when i want to import it in python intepreter i get the folowing error.

```python
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yagmail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/yagmail/__init__.py", line 6, in <module>
    from .yagmail import SMTP
  File "/usr/lib/python3.5/site-packages/yagmail/yagmail.py", line 7, in <module>
    import keyring
  File "/usr/lib/python3.5/site-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 158, in <module>
    init_backend()
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 58, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 66, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/usr/lib/python3.5/site-packages/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/keyring/backend.py", line 179, in get_all_keyring
    _load_backends()
  File "/usr/lib/python3.5/site-packages/keyring/backend.py", line 139, in _load_backends
    list(map(_load_backend, backends))
  File "/usr/lib/python3.5/site-packages/keyring/backend.py", line 124, in _load_backend
    mod = importlib.import_module('.'+name, package)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.5/site-packages/keyring/backends/Gnome.py", line 4, in <module>
    import gi
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
>>> 
```

**Comment by schef** [comment]
I installed python-keyring pygobject-devel  python-crypto  python-gobject and now it works.

**Comment by bretcj7** [comment]
Similar issue when gi is called from matplotlib.  The above suggestion did not work.
