### ISSUE TITLE
Error report while start my application

### ISSUE THREAD

**Issue by ThrowSyntaxError** [kootenpv/yagmail#253]
**here is some error message:**
Exception ignored in: <function SMTP.__del__ at 0x7f60bed18430>
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/yixing_39/lib/python3.8/site-packages/yagmail/sender.py", line 261, in __del__
  File "/root/anaconda3/envs/yixing_39/lib/python3.8/site-packages/yagmail/sender.py", line 203, in close
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**description:**
I'm gonna test the function of sending email by using yagmail module in my app,but when I running my project the above problem occurred. dose it exist an error in source code? or just my fault? How should I solve this problem？

_**here is the code for the corresponding location above:**_
```py
 def close(self):
        """ Close the connection to the SMTP server """
        self.is_closed = True
        try:
            self.smtp.quit()
        except (TypeError, AttributeError, smtplib.SMTPServerDisconnected):  # line 203
            pass
```

**Comment by kootenpv** [comment]
How are you using yagmail

**Comment by ThrowSyntaxError** [comment]
> Try creating the smtp client right before sending all the time

Acturally I just create a new mialManager instance in file app.py and not using sendMail function yet. I've switched to smptlib module in my app temporarily, but I still wanna figure it out. I notice that sometimes you need create a connection by using smtplib.SMTP_SSL() instead of smtplib.SMTP() in smtplib module, is this one of the possible reasons?
