### ISSUE TITLE
It throws an exception when running on windows 10 cmd.exe after packed into an .exe script by pyinstaller command

### ISSUE THREAD

**Issue by xiawenniu** [kootenpv/yagmail#270]
OS: windows 10
python version: 3.12.0
package version:  0.15.293
pyinstaller version： 6.1.0

Description: I use pyinstaller to translate this python script to executable script on windows 10 and run it, but an exception is avoided below:

Exception ignored in: <function SMTP.__del__ at 0x00000262924C8900>
Traceback (most recent call last):
  File "yagmail\sender.py", line 261, in __del__
  File "yagmail\sender.py", line 203, in close
TypeError: catching classes that do not inherit from BaseException is not allowed

Code like this :

yag = yagmail.SMTP(user=sender_account, password=sender_password, host=smtp_server)
try:
        yag.send(to=row[EMAIL_INDEX_NAME], subject=subject, contents=content, attachments= 
                 attachment_path)
        time.sleep(30)
    except BaseException as e:
        print(e)
        
yagmail.SMTP.close

**Comment by xiawenniu** [comment]
When running in python environment, it doesn't throw this exception.
