### ISSUE TITLE
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:579)

### ISSUE THREAD

**Issue by opsconquer** [kootenpv/yagmail#97]
Traceback (most recent call last):
  File "yyy.py", line 7, in <module>
    yag = yagmail.SMTP(user='xxxx@xxxx.com', password='xxxx', host='xxx.xxx.163.com', port='25')
  File "/usr/lib/python2.7/site-packages/yagmail/sender.py", line 78, in __init__
    self.login(password)
  File "/usr/lib/python2.7/site-packages/yagmail/sender.py", line 192, in login
    self.smtp = self.connection(self.host, self.port, **self.kwargs)
  File "/usr/lib64/python2.7/smtplib.py", line 789, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 795, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib64/python2.7/ssl.py", line 936, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:579)

How to solve this problem？

**Comment by radoslawoska** [comment]
Hi, had the same issue
change the port 
for example: port=465

**Comment by yangzhongwell** [comment]
@radoslawoska  after change the port 465, it worked，but why ？
smtplib.SMTP use port 25，smtplib.SMTP_SSL use 465

**Comment by kootenpv** [comment]
If you select `use_ssl=True`, it will switch the port.
